name: 'clean work dirs'
description: 'Clean working directories after previous jobs'
branding:
  icon: 'archive'
  color: 'grey'
inputs:
  home:
    description: 'clean home directory'
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: clean home dir
      run: |
        if [ "${{ inputs.home }}" == "true" ]; then
          (
            cd ~
            # NOTE: ls on macosx does not support long key names, e.g. --almost-all
            for f in $(ls -A); do
              rm -rf $f
            done
          )
        fi
      shell: bash
