name: ci
on: [push, pull_request]
jobs:
  linux_container:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {runson: windows-latest, os: , codename: , image_owner: , package_type: }
          - {runson: macos-latest, os: , codename: , image_owner: , package_type: }
          - {runson: ubuntu-latest, os: , codename: , image_owner: , package_type: }
          - {runson: ubuntu-latest, os: debian, codename: stretch, image_owner: , package_type: deb}
          - {runson: ubuntu-latest, os: debian, codename: buster, image_owner: , package_type: deb}
          - {runson: ubuntu-latest, os: ubuntu, codename: bionic, image_owner: , package_type: deb}
          - {runson: ubuntu-latest, os: ubuntu, codename: focal, image_owner: , package_type: deb}
    runs-on: ${{ matrix.runson }}
    container: ${{ matrix.image_owner }}${{ matrix.os }}${{ matrix.os != '' || ':' }}${{ matrix.codename }}
    name: ${{ matrix.os == '' && 'ubuntu-latest' || 'linux container - ' }}${{ matrix.image_owner }}${{ matrix.os }}${{ matrix.os != '' || ':' }}${{ matrix.codename }}
    steps:
      - name: add garbage
        run: |
          touch ~/.hidden_file
          mkdir -p ~/.hidden_dir
          touch ~/file
          mkdir -p ~/dir
      - name: cehckout repo
        uses: actions/checkout@v2
      - name: clean
        uses: ./
        with:
          home: true
      - name: check no garbage
        run: |
          [ ! -f "~/.hidden_file" ] &&
          [ ! -d "~/.hidden_dir" ] &&
          [ ! -f "~/file" ] &&
          [ ! -d "~/dir" ]
