name: ci
on: [push, pull_request]
jobs:
  linux_container:
    strategy:
      fail-fast: false
      matrix:
        include:
          # - {runs-on: windows-latest, os: , codename: , image_owner: , package_type: }
          # - {runs-on: macos-latest, os: , codename: , image_owner: , package_type: }
          # - {runs-on: ubuntu-latest, os: , codename: , image_owner: , package_type: }
          # - {runs-on: ubuntu-latest, os: debian, codename: stretch, image_owner: , package_type: deb}
          # - {runs-on: ubuntu-latest, os: debian, codename: buster, image_owner: , package_type: deb}
          # - {runs-on: ubuntu-latest, os: ubuntu, codename: bionic, image_owner: , package_type: deb}
          # - {runs-on: ubuntu-latest, os: ubuntu, codename: focal, image_owner: , package_type: deb}
    runs-on: ${{ matrix.runs-on }}
    container: ${{ matrix.image_owner }}${{ matrix.os }}${{ matrix.os != '' && ':' || '' }}${{ matrix.codename }}
    name: ${{ matrix.os == '' && matrix.runs-on || 'linux container - ' }}${{ matrix.image_owner }}${{ matrix.os }}${{ matrix.os != '' && ':' || '' }}${{ matrix.codename }}
    steps:
      - name: add garbage
        run: |
          # NOTE: creating files in home dir is only possible on self-hosted runners, for some reason
          # echo "blabla" > ~/.hidden_file
          # mkdir -p ~/.hidden_dir
          # echo "blabla" > touch ~/file
          # mkdir -p ~/dir
          # [ -f "~/.hidden_file" ] || echo "~/.hidden_file not found" && exit 1
          # [ -d "~/.hidden_dir" ] || echo "~/.hidden_dir not found" && exit 1
          # [ -f "~/file" ] || echo "~/file not found" && exit 1
          # [ -d "~/dir" ] || echo "~/dir not found" && exit 1
        shell: bash
      - name: cehckout repo
        uses: actions/checkout@v2
      - name: clean
        uses: ./
        with:
          home: true
      - name: check no garbage
        run: |
          # [ ! -f "~/.hidden_file" ] || echo "~/.hidden_file found" && exit 1
          # [ ! -d "~/.hidden_dir" ] || echo "~/.hidden_dir found" && exit 1
          # [ ! -f "~/file" ] || echo "~/file found" && exit 1
          # [ ! -d "~/dir" ] || echo "~/dir found" && exit 1
        shell: bash
